image: cypress/browsers:node16.5.0-chrome94-ff93
options:
  max-time: 120

pipelines:
  default:
    - parallel:
        - step:
            name: DIETLY TESTS
            caches:
              - node
            script:
              - npm install
              - npm run cy:run
            caches:
              - node
